#!/bin/bash
# UkCvs.net Cadet Project dm500 build script for Ubuntu LTS 32bit - 1st May 2016

UKCVS_BRANCH="Cadet"

buildstart=`date +%s`
CURRENT_PATH=`pwd`
PROJECT_PATH="$CURRENT_PATH/ukcvs-$UKCVS_BRANCH"

if [ `readlink /bin/sh` = "dash" ]; then
	echo
	echo "WARNING - i am reconfiguring your system to use bash as shell"
	echo "command: 'sudo dpkg-reconfigure dash', select YES to reverse"
	sudo ln -sf bash /bin/sh
	sudo ln -sf dash /bin/sh.distrib
fi

echo
echo "I am testing that you have the required tools installed"
for pkg in automake git subversion cvs libtool make g++ flex bison mtd-utils diffutils \
	pkg-config patch squashfs-tools zlib1g-dev ccache gawk bzip2 dialog expect-dev zip; do
	if [ $(dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
		sudo apt-get install -y $pkg
	else
		echo "checking for $pkg ... yes"
	fi
done

echo
if [ ! -d $CURRENT_PATH/Archive ]; then
	echo "creating Archive folder"
	mkdir -p $CURRENT_PATH/Archive
else
	echo "checking for Archive folder ... yes"
fi
if [ ! -d $PROJECT_PATH/dreambox ]; then
	echo "creating dreambox folder"
	mkdir -p $PROJECT_PATH/dreambox
else
	echo "checking for dreambox folder ... yes"
fi

dialog \
--clear --cancel-label "Exit" --backtitle "UkCvs.net $UKCVS_BRANCH Project Build Script - dm500" \
--colors --title "\Z4 [ PLEASE CHOOSE AN OPTION ] \Zn" \
--menu "\n  Please select what type of image to build \n\n\
 You can use the UP/DOWN arrow navigation keys\n\
 or keypress C,M,U,N as the choice of hot keys" 15 50 8 \
Create "make local only build - distclean" \
Modify "make local only build - mostlyclean" \
Update "online >> local build - distclean" \
New "online checkout build - deleted" 2>/tmp/ukcvs

buildenv="Exit"
buildclean="distclean"
menuitem=$(</tmp/ukcvs)

case $menuitem in
	Create) buildenv="Create";;
	Modify) buildenv="Modify";buildclean="mostlyclean";;
	Update) buildenv="Update";;
	New) buildenv="New";;
esac

[ -f /tmp/ukcvs ] && rm /tmp/ukcvs
if [ $buildenv = "Exit" ] ; then 
	echo "Bye"
	exit 0
fi

echo
if [ ! -d $PROJECT_PATH/cdk ] || [ $buildenv = "New" ]; then
	echo "checking out new build environment"
	[ -d $PROJECT_PATH ] && rm -rf $PROJECT_PATH
	git clone -b $UKCVS_BRANCH git://github.com/UkCvs/ukcvs.git $PROJECT_PATH
	cd $PROJECT_PATH
	git status
elif [ $buildenv = "Update" ]; then
	echo "updating current build environment"
	cd $PROJECT_PATH
	git pull
elif [ $buildenv = "Create" ] || [ $buildenv = "Modify" ]; then
	echo "using the local build environment"; echo
	echo "Display Latest Info for $UKCVS_BRANCH Project environment";echo
	cd $PROJECT_PATH
	git log -1 && echo && git status
	sleep 10
else
	echo "Bye"
	exit 0
fi

echo
cd $PROJECT_PATH/cdk

if [ -f $PROJECT_PATH/cdk/Makefile-archive ]; then
	echo "$buildclean is cleaning the local build environment, please wait..."
	make $buildclean > /dev/null 2>&1
fi

./autogen.sh;
./configure \
	--prefix=$PROJECT_PATH/dreambox \
	--with-cvsdir=$PROJECT_PATH \
	--with-archivedir=$CURRENT_PATH/Archive \
	--with-boxtype=dreambox \
	--with-boxmodel=dm500 \
	--with-filesystems="nfs,cifs,smbfs" \
	--with-defaultlocale=english \
	--with-flashtool=expert \
	--disable-pictureviewer \
	--disable-tuxmail \
	--enable-dvbsnoop \
	--enable-dreambox-serial-console \
	--enable-fx2-tetris \
	--enable-shellexec \
	--enable-openvpn \
	--enable-msgbox \
	--enable-input \
	--enable-eraseall \
	--enable-automount \
	--enable-freesatepg \
	--enable-upnp

make flash-neutrino-squashfs 2>$PROJECT_PATH/buildlog.txt

builddate=`date +%Y%m%d-%H%M`
buildstop=$(expr `date +%s` - $buildstart)
buildhour=$(expr $buildstop / 3600)
buildstop=$(expr $buildstop % 3600)
buildmins=$(expr $buildstop / 60)
buildsecs=$(expr $buildstop % 60)

cd $PROJECT_PATH
revision=$(git log -1 | grep '^commit' | cut -d ' ' -f2 | cut -c1-7)

if [ -f dreambox/cdkflash/complete-neutrino.img ]; then
	buildfile="ukcvs-$UKCVS_BRANCH-dm500-$builddate-$revision.img"
	cp dreambox/cdkflash/complete-neutrino.img $buildfile
	md5sum -b $buildfile > MD5SUM
	rm -f ukcvs-$UKCVS_BRANCH-dm500-$revision.zip
	zip -j ukcvs-$UKCVS_BRANCH-dm500-$revision.zip $buildfile MD5SUM
	dialog \
	--clear --backtitle "UkCvs.net $UKCVS_BRANCH Project Build Script - dm500" \
	--colors --title "\Z4[ Github:$revision $buildenv Build Finished ]\Zn" \
	--msgbox "ukcvs-$UKCVS_BRANCH-dm500-$builddate-$revision.img\n\n
	`date`\nTotal Time: $buildhour hours $buildmins mins $buildsecs secs\n" 8 52
else
	dialog \
	--clear --backtitle "UkCvs.net $UKCVS_BRANCH Project Build Script - dm500" \
	--colors --title "\Z4[ Github:$revision $buildenv Build Finished ]\Zn" \
	--msgbox " ERROR: Build failed to create an image\n\n
	`date`\n Total Time: $buildhour hours $buildmins mins $buildsecs secs\n" 8 52
fi
echo

exit 0

